import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body>
        <div id="page">
          <header id="masthead" className="site-header">
            <div className="logo">Memoアプリ</div>
          </header>
          <main id="main" className="main">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
